# Generated by Django 3.0.5 on 2020-04-05 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scac', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('MC', models.IntegerField(blank=True, null=True)),
                ('DOT', models.IntegerField(blank=True, null=True)),
                ('FEIN', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('origin_country', models.CharField(max_length=30)),
                ('origin_state', models.CharField(max_length=30)),
                ('origin_city', models.CharField(max_length=30)),
                ('destination_country', models.CharField(max_length=30)),
                ('destination_state', models.CharField(max_length=30)),
                ('destination_city', models.CharField(max_length=30)),
                ('pick_up_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('carrier_rate', models.IntegerField()),
                ('carrier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Carrier')),
            ],
        ),
    ]
