# Generated by Django 3.0.5 on 2020-04-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='carrier_rate',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
