# Generated by Django 3.0.5 on 2020-04-05 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_superuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
